# Intro to Python

We can write markdown and python code here. ctrl+enter to execute

In [13]:
a=11
print(a,end=",")
print(12)
print(13);

11,12
13


In [15]:
a=12
a=12.3
print(a)


12.3


In [16]:
print(a)

12.3


In [18]:
x=12
y=7
print(x/y)
print(x//y)

1.7142857142857142
1


In [13]:
a="This is a string and it is immutable"
print(a)
print(len(a))
print(type(a))
print(a[0])
print(a+" right");

This is a string and it is immutable
36
<class 'str'>
T
This is a string and it is immutable right


In [5]:
#there are some methods on string

In [7]:
#taking input

a=int(input());
print(type(a));

 22


<class 'int'>


In [10]:
#slicing

a="hello world"
print(a[0:5])
print(a[0:])
print(a[:8])

hello
hello world
hello wo


In [14]:
#tupple is immutable and even slicing works
t=(1,"hello",2)
print(type(t))
print(1 in t);


<class 'tuple'>
True


In [16]:
#we have boolean variable in python and all the operators
a=True;
print(a)

True


In [ ]:
#indentation matters in python

In [29]:
#loops

i=0;
while(i<5):
 print(i,end=" ");
 i=i+1;
print("done printing")

for i in range(2,10,2):
    print(i,end=" ")

print("");
a='value';
for it in a:
    print(it,end=" ");

0 1 2 3 4 done printing
2 4 6 8 
v a l u e 

In [32]:
#functions in python


def sum(x,y):
    return x+y,x-y

x=10
y=11;
print(sum(x,y)[0])

21


In [4]:
#Arrays
a=[1,"helo",3,4]
x=[['1','2','3'],[4,5,6]]
print(x[1][0])
b=list(a)


#another way of creating array
array=[i for i in range(10)]
print(array)

print(type(a))
print(type(b))

print(a[1])
del a[0:4]

print(a)

#even slicing works,methods like append(value),insert(pos,value) works fine,for deleting we have pop(),pop(index),remove(value)

4
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>
<class 'list'>
helo
[]


In [44]:
#dictonaries
d={};
d[23]=44
d["h"]=9

p={44:3,43:5}

print(d)
print(p)


{23: 44, 'h': 9}
{44: 3, 43: 5}


In [17]:
#importing module in python

import math as m

print(m.sqrt(16))


4.0


In [27]:
#numpy library
#numpy arrays are more faster than lists why? because we have compact size in numpy,by having same datatype throught the the array

import numpy as np
l=[1,2,3]
p=[1,2,"3"]
np.array(l)

m=np.array([9,9,9])
print(m)

#there are methods on numpy
q=np.zeros(10,int)
print(q)

#we can also create multidimensional arrays as well
x=np.zeros((4,3))
print(x)

#even slicing works here exactly it worked for list

[9 9 9]
[0 0 0 0 0 0 0 0 0 0]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [38]:
#numpy operations
a=np.array([1,2,3])
b=np.array([5,6,7])
print(a+2)
print(a+b)
#all the operation can be carried out like - * / **

print(a.mean())
print(a.sum())


a=np.array([1,2,3])
b=np.array([5,6,7])


print('-------')
#complexe calculations can be carried out easily using numpy
print((a-a.mean()).mean())

[3 4 5]
[ 6  8 10]
2.0
6
-------
0.0


In [3]:
#pandas
import pandas as pd
import numpy as np

iris=pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data')


df=iris.copy()
df.head(4)

5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa

In [4]:
df.columns=['sl','sw','pl','pw','flower_type']

In [12]:
print(df)

      sl   sw   pl   pw     flower_type
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]


In [12]:
print(df.shape)
print(df.dtypes);

(149, 5)
sl             float64
sw             float64
pl             float64
pw             float64
flower_type     object
dtype: object


In [13]:
df.describe()

sl          sw          pl          pw
count  149.000000  149.000000  149.000000  149.000000
mean     5.848322    3.051007    3.774497    1.205369
std      0.828594    0.433499    1.759651    0.761292
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.400000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [14]:
#accessing particular colum
df.sl
df["sl"]

0      4.9
1      4.7
2      4.6
3      5.0
4      5.4
      ... 
144    6.7
145    6.3
146    6.5
147    6.2
148    5.9
Name: sl, Length: 149, dtype: float64

In [15]:
df.isnull().sum()

sl             0
sw             0
pl             0
pw             0
flower_type    0
dtype: int64

In [16]:
#to acess some data in between
df.iloc[0:4,0:3]

sl   sw   pl
0  4.9  3.0  1.4
1  4.7  3.2  1.3
2  4.6  3.1  1.5
3  5.0  3.6  1.4

In [17]:
#df.drop(0,inplace=True)
df.head()
df.index[2]
df.drop(df.index[0],inplace=True)
df.head()

sl   sw   pl   pw  flower_type
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa
5  4.6  3.4  1.4  0.3  Iris-setosa

In [18]:
df[df.sl>5]
c1=df[df.flower_type=='Iris-setosa']
print(c1)

     sl   sw   pl   pw  flower_type
1   4.7  3.2  1.3  0.2  Iris-setosa
2   4.6  3.1  1.5  0.2  Iris-setosa
3   5.0  3.6  1.4  0.2  Iris-setosa
4   5.4  3.9  1.7  0.4  Iris-setosa
5   4.6  3.4  1.4  0.3  Iris-setosa
6   5.0  3.4  1.5  0.2  Iris-setosa
7   4.4  2.9  1.4  0.2  Iris-setosa
8   4.9  3.1  1.5  0.1  Iris-setosa
9   5.4  3.7  1.5  0.2  Iris-setosa
10  4.8  3.4  1.6  0.2  Iris-setosa
11  4.8  3.0  1.4  0.1  Iris-setosa
12  4.3  3.0  1.1  0.1  Iris-setosa
13  5.8  4.0  1.2  0.2  Iris-setosa
14  5.7  4.4  1.5  0.4  Iris-setosa
15  5.4  3.9  1.3  0.4  Iris-setosa
16  5.1  3.5  1.4  0.3  Iris-setosa
17  5.7  3.8  1.7  0.3  Iris-setosa
18  5.1  3.8  1.5  0.3  Iris-setosa
19  5.4  3.4  1.7  0.2  Iris-setosa
20  5.1  3.7  1.5  0.4  Iris-setosa
21  4.6  3.6  1.0  0.2  Iris-setosa
22  5.1  3.3  1.7  0.5  Iris-setosa
23  4.8  3.4  1.9  0.2  Iris-setosa
24  5.0  3.0  1.6  0.2  Iris-setosa
25  5.0  3.4  1.6  0.4  Iris-setosa
26  5.2  3.5  1.5  0.2  Iris-setosa
27  5.2  3.4  1.4  0.2  Iris

In [19]:
#iloc is doing it by position and loc is doing it by place
print(df.iloc[0])   
print(df.loc[4])

sl                     4.7
sw                     3.2
pl                     1.3
pw                     0.2
flower_type    Iris-setosa
Name: 1, dtype: object
sl                     5.4
sw                     3.9
pl                     1.7
pw                     0.4
flower_type    Iris-setosa
Name: 4, dtype: object


In [20]:
#add a row
df.loc[149]=[1,2,3,4,'Iris-setosa']
df.tail()

sl   sw   pl   pw     flower_type
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica
149  1.0  2.0  3.0  4.0     Iris-setosa

In [26]:
df.index
df.reset_index(drop=True,inplace=True)
df.index

RangeIndex(start=0, stop=149, step=1)

In [31]:
#removing colums
df.drop('sl',axis=1,inplace=True)

#another way
# del df['sl']

print("removed")

removed


In [30]:
print(df)

      sw   pl   pw     flower_type
0    3.2  1.3  0.2     Iris-setosa
1    3.1  1.5  0.2     Iris-setosa
2    3.6  1.4  0.2     Iris-setosa
3    3.9  1.7  0.4     Iris-setosa
4    3.4  1.4  0.3     Iris-setosa
..   ...  ...  ...             ...
144  2.5  5.0  1.9  Iris-virginica
145  3.0  5.2  2.0  Iris-virginica
146  3.4  5.4  2.3  Iris-virginica
147  3.0  5.1  1.8  Iris-virginica
148  2.0  3.0  4.0     Iris-setosa

[149 rows x 4 columns]


In [36]:
df=iris.copy()
df.columns=['sl','sw','pl','pw','flower_type']

#how to add colums
df["diff_pl_pw"]=df["pl"]-df["pw"]
df.tail()

sl   sw   pl   pw     flower_type  diff_pl_pw
144  6.7  3.0  5.2  2.3  Iris-virginica         2.9
145  6.3  2.5  5.0  1.9  Iris-virginica         3.1
146  6.5  3.0  5.2  2.0  Iris-virginica         3.2
147  6.2  3.4  5.4  2.3  Iris-virginica         3.1
148  5.9  3.0  5.1  1.8  Iris-virginica         3.3

In [8]:
df.iloc[2:4,1:3]=np.nan
df.head()

sl   sw   pl   pw  flower_type
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  NaN  NaN  0.2  Iris-setosa
3  5.0  NaN  NaN  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [11]:
df.dropna(inplace=True)
df.head()
df.reset_index(drop=True,inplace=True);
df.head()

sl   sw   pl   pw  flower_type
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  5.4  3.9  1.7  0.4  Iris-setosa
3  4.6  3.4  1.4  0.3  Iris-setosa
4  5.0  3.4  1.5  0.2  Iris-setosa

In [9]:
df.iloc[2:4,1:3]=np.nan
df.head()
df.sw.fillna(df.sw.mean(),inplace=True)
df.pl.fillna(df.pl.mean(),inplace=True)
df.head()

sl        sw        pl   pw  flower_type
0  4.9  3.000000  1.400000  0.2  Iris-setosa
1  4.7  3.200000  1.300000  0.2  Iris-setosa
2  4.6  3.046939  3.806122  0.2  Iris-setosa
3  5.0  3.046939  3.806122  0.2  Iris-setosa
4  5.4  3.900000  1.700000  0.4  Iris-setosa

In [36]:
df["Gender"]="Female"
df.iloc[0:10, 5 ]="Male"

def f(s):
    if s== "Male":
        return 0
    else:
        return 1
    
df["sex"]=df.Gender.apply(f)
del df["Gender"]
df.tail()



sl   sw   pl   pw     flower_type  sex
144  6.7  3.0  5.2  2.3  Iris-virginica    1
145  6.3  2.5  5.0  1.9  Iris-virginica    1
146  6.5  3.0  5.2  2.0  Iris-virginica    1
147  6.2  3.4  5.4  2.3  Iris-virginica    1
148  5.9  3.0  5.1  1.8  Iris-virginica    1

In [ ]:
#intro to titanicdatasets
